#!/usr/bin/env node
// Generate docs/tools.md from the vendored Soundiiz OpenAPI spec.
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { getSpecIndex } from '../src/core/spec.js';
import { readToolName, writeToolName } from '../src/utils/toolNames.js';

interface CuratedRow {
  name: string;
  tier: 'read' | 'write-medium' | 'write-destructive' | 'local';
  description: string;
}

const CURATED: CuratedRow[] = [
  { name: 'soundiiz_me', tier: 'read', description: 'Get the current authenticated Soundiiz user.' },
  {
    name: 'soundiiz_auth_status',
    tier: 'local',
    description: 'Check whether the configured key authenticates against /v1/me.',
  },
  {
    name: 'soundiiz_auth_set',
    tier: 'local',
    description: 'Set/persist the Soundiiz API key (according to keyStore mode).',
  },
  {
    name: 'soundiiz_auth_clear',
    tier: 'local',
    description: 'Clear the API key from memory and persistent store.',
  },
  {
    name: 'soundiiz_syncs_list',
    tier: 'read',
    description: 'List Soundiiz syncs as compact rows. Auto-paginates by default.',
  },
  { name: 'soundiiz_sync_get', tier: 'read', description: 'Get a single sync with lastExecutionResult.' },
  {
    name: 'soundiiz_syncs_overview',
    tier: 'read',
    description: 'Counts by status/frequency/platform pair, dueSoon, recentFailures.',
  },
  { name: 'soundiiz_syncs_due', tier: 'read', description: 'Syncs due to run within a window.' },
  {
    name: 'soundiiz_sync_trigger',
    tier: 'write-medium',
    description: 'Trigger a sync (confirmation token, then execute).',
  },
  {
    name: 'soundiiz_sync_delete',
    tier: 'write-destructive',
    description: 'Delete a sync (confirmation token, then execute).',
  },
  {
    name: 'soundiiz_smartlinks_list',
    tier: 'read',
    description: 'List SmartLinks as compact rows. Auto-paginates by default.',
  },
  { name: 'soundiiz_smartlink_get', tier: 'read', description: 'Get a single SmartLink with all platform links.' },
  {
    name: 'soundiiz_smartlinks_overview',
    tier: 'read',
    description: 'Counts by status/category/platform, recently-updated.',
  },
  {
    name: 'soundiiz_smartlink_delete',
    tier: 'write-destructive',
    description: 'Delete a SmartLink (confirmation token, then execute).',
  },
  {
    name: 'soundiiz_cache_invalidate',
    tier: 'local',
    description: 'Invalidate MCP-local cache (scope=all by default).',
  },
];

function tierLabel(tier: CuratedRow['tier']): string {
  switch (tier) {
    case 'read':
      return 'read';
    case 'write-medium':
      return 'write (medium-risk)';
    case 'write-destructive':
      return 'write (destructive)';
    case 'local':
      return 'local-only';
  }
}

function main(): void {
  const index = getSpecIndex();
  const out: string[] = [];
  out.push('# Tool Catalog');
  out.push('');
  out.push('_Generated by `npm run generate:tools-docs`. Do not edit by hand._');
  out.push('');
  out.push('## Curated Tools');
  out.push('');
  out.push('| Tool | Tier | Description |');
  out.push('| ---- | ---- | ----------- |');
  for (const row of CURATED) {
    out.push(`| \`${row.name}\` | ${tierLabel(row.tier)} | ${row.description} |`);
  }
  out.push('');
  out.push('## Auto-generated Tools (from OpenAPI spec)');
  out.push('');
  out.push('| Tool | Method | Path | Tag |');
  out.push('| ---- | ------ | ---- | --- |');
  for (const op of index.operations.values()) {
    const name = op.method === 'GET' ? readToolName(op.operationId) : writeToolName(op.operationId);
    out.push(`| \`${name}\` | ${op.method} | \`${op.path}\` | ${op.tags[0] ?? '-'} |`);
  }
  out.push('');
  out.push('## Raw Tools (opt-in)');
  out.push('');
  out.push('| Tool | Description |');
  out.push('| ---- | ----------- |');
  out.push('| `soundiiz_call` | Call any operationId directly. Disabled by default. |');
  out.push('| `soundiiz_list_operations` | List all available operationIds from the spec. |');
  out.push('');

  const target = path.resolve(process.cwd(), 'docs/tools.md');
  writeFileSync(target, out.join('\n'), 'utf8');
  console.log(`Wrote ${target}`);
}

main();
